// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmlddttzapuzvotmaxzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbGRkdHR6YXB1enZvdG1heHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTIyNzEsImV4cCI6MjA2NDE4ODI3MX0.vItVhFGsvbUtrT5QF5ErBqCNBBrUy8J9-Cp8-OOa9TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);